export const QuestionnaireActionTypes = {
  SET_TEST: 'SET_TEST',
  SET_ACTIVE_QUESTION: 'SET_ACTIVE_QUESTION',
  SET_NEXT_QUESTION: 'SET_NEXT_QUESTION',
  SET_PREV_QUESTION: 'SET_PREV_QUESTION',
  COUNT_RESULT_POINTS: 'COUNT_RESULT_POINTS',
}
