export const QuestionnaireActionTypes = {
  SET_TEST: 'SET_TEST',
  SET_CURRENT_QUESTION: 'SET_CURRENT_QUESTION',
  SET_QUESTION_RESULT: 'SET_QUESTION_RESULT',
  COUNT_RESULT_POINTS: 'COUNT_RESULT_POINTS',
}
